version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
    - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
  server:
    image: osd-python
    ports:
      - "3002:3002"
    volumes:
      - type: bind
        source: /Users/paulpinter/Library/CloudStorage/GoogleDrive-paul.pinter.is@gmail.com/My Drive/Data Set/Ba
        target: /files
    command: ["python", "/osd/controller/server.py"]
    environment:
      - BASE_PATH=/files
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - DB_CONNECTION=postgresql+psycopg2://postgres@db:5432/postgres
    depends_on:
      - kafka
      - db
  listener:
    image: osd-python
    ports:
      - "3003:3003"
    volumes:
      - type: bind
        source: /Users/paulpinter/Library/CloudStorage/GoogleDrive-paul.pinter.is@gmail.com/My Drive/Data Set/Ba
        target: /files
    command: sh -c "
      sleep 30 &&
      python /osd/controller/listener.py"
    environment:
      - BASE_PATH=/files
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - DB_CONNECTION=postgresql+psycopg2://postgres@db:5432/postgres
    depends_on:
      - kafka
      - db
  batch:
    ports:
      - "3004:3004"
    image: osd-python
    volumes:
      - type: bind
        source: /Users/paulpinter/Library/CloudStorage/GoogleDrive-paul.pinter.is@gmail.com/My Drive/Data Set/Ba
        target: /files
    command: ["python", "/osd/controller/batch.py"]
    environment:
      - BASE_PATH=/files
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - DB_CONNECTION=postgresql+psycopg2://postgres@db:5432/postgres
    depends_on:
      - kafka
      - db
  db:
    image: postgres:latest
    ports:
      - "32768:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
